mxcp: 1

projects:
  swiss-mxcp-server:
    profiles:
      prod:
        plugin:
          config: {}

# Configure transport to bind to all interfaces (critical for App Runner)
transport:
  provider: streamable-http
  http:
    host: 0.0.0.0
    port: 8000
