version: 2

models:
  - name: swiss_companies
    description: "Swiss business registry companies with 1,000 synthetic companies"
    config:
      tags: ["swiss-companies"]
    # Row count test is in tests/test_company_counts.sql
    columns:
      - name: UID
        description: "Unique Identification Number"
        tests:
          - unique
          - not_null
          # Test UID is not empty string
          - dbt_utils.not_empty_string
      - name: CompanyName
        description: "Company name"
        tests:
          - not_null
          - unique
      - name: LegalForm
        description: "Legal form of the company"
        tests:
          - not_null
          - accepted_values:
              values: ['AG', 'GmbH', 'Einzelfirma', 'Kollektivgesellschaft', 'Verein', 'Stiftung', 'SA', 'LLC', 'Inc.', 'Ltd.', 'Corp.']
              config:
                severity: error
      - name: Canton
        description: "Swiss canton where company is located"
        tests:
          - not_null
          - accepted_values:
              values: [
                'Zürich', 'Bern', 'Geneva', 'Basel-Stadt', 'Basel-Landschaft', 
                'Aargau', 'St. Gallen', 'Grisons', 'Lucerne', 'Ticino',
                'Valais', 'Vaud', 'Thurgau', 'Solothurn', 'Neuchâtel',
                'Fribourg', 'Schaffhausen', 'Appenzell Ausserrhoden',
                'Appenzell Innerrhoden', 'Glarus', 'Jura', 'Obwalden',
                'Nidwalden', 'Schwyz', 'Uri', 'Zug'
              ]
              config:
                severity: error
      - name: RegistrationDate
        description: "Date when company was registered"
        tests:
          - not_null
      - name: ShareCapitalCHF
        description: "Share capital in Swiss Francs"
        tests:
          - not_null
      - name: IndustryCode
        description: "Industry classification code"
        tests:
          - not_null
          # Test that industry codes are numeric strings
          - dbt_utils.not_empty_string
      - name: IndustryDescription
        description: "Industry classification description"
        tests:
          - not_null
          - dbt_utils.not_empty_string
      - name: Employees
        description: "Number of employees"
        tests:
          - not_null
